# Generated by Django 3.2.22 on 2023-10-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='user',
            field=models.IntegerField(blank=True, help_text='The user who created this revision.', null=True, verbose_name='insurance.User'),
        ),
    ]
