# Generated by Django 3.2.6 on 2023-10-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='user',
            on_delete=models.DO_NOTHING,
        ),
    ]
